### PR TITLE
[Issue #2]: Created swagger codegen module to generate notebooks.

### PR DESCRIPTION
**Pull request by Lull3rSkat3r**
This project will contain a swagger module for generating notebooks and converting them into microservices. Work to be done:
- [x] Create a swagger module to generate notebooks
- [x] Bundle the notebooks into a docker container
- [x] Implement the swagger pet store API to provide a comprehensive example

### CODE REVIEW

**Comment by parente** [comment]
Is this ready to go in? Need more pet store impl?

**Comment by Lull3rSkat3r** [comment]
Yes, we still need pet store impl. Have some work items I need to open before we can complete the implementation. Will open those today.

**Comment by parente** [comment]
TODOs on this PR to get it in:
- [x] Copyright header for Jupyter
- [x] pip install 0.2.0 kernel_gateway
- [x] notebook showing the pet store implementation (but not with error codes, headers, etc. see issue #2 )

**Comment by Lull3rSkat3r** [comment]
I have some changes to the kernel gateway project I am going to push. Will update here when I open the PR

**Comment by Lull3rSkat3r** [comment]
Issue jupyter-incubator/kernel_gateway/pull/52 and PR jupyter-incubator/kernel_gateway/pull/54 are the only bits needed to be merged into the kernel gateway for this demo to fully work. 

@parente, since the form parameter feature is not in the 0.2.0 release should we do anything special in the Dockerfile or just assume the changes will get there eventually?

**Comment by parente** [comment]
We can release a 0.2.1. That's not hard. What's the alternative with the Dockerfile?

**Comment by Lull3rSkat3r** [comment]
I was thinking we could point to the repo to install and when 0.3.0 is cut update the Dockerfile to do a normal pip install.

**Comment by parente** [comment]
Pointing to master is fine for a demo. Go with that and we'll update later with 0.3.0 like you said.

**Comment by Lull3rSkat3r** [comment]
Alright, @parente this is GTG :fire: .

**Comment by parente** [comment]
Since this is a demo, I'm going to put this in and then give it a shot. If there's problems, I'll open issues.

**Pull request merged**
