### PR TITLE
[Issue 4] Port the scotch api example in kernel_gateway to R and Julia

### PR DESCRIPTION
**Pull request by poplav**
(c) Copyright IBM Corp. 2015

### CODE REVIEW

**Comment by parente** [comment]
Cool. I'll give this a shot today or tomorrow.

**Comment by parente** [comment]
It's sooooo neat to see this working. Nice job.

Here's a few minor suggestions to put icing on the cake:
- Clear the outputs in both notebooks before committing. Makes the notebook easier to follow on GitHub in this case where the output will be coming back over HTTP.
- RCurl should already be installed (https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile#L82). Is it not working?
- For the other things you're installing at the top of the notebooks, move those install steps to the Dockerfile so they're done once at build time, not at runtime. Refer to how R packages are installed using conda and Julia packages are installed properly in the docker-stacks datascience Dockerfile for help.
- Add another line at the bottom of the README indicating how the user can access the running server after the `make r_api` or `make julia_api` commands. Something like "Point your web browser to http://<your docker host ip>:8888/scotches, http://<your docker host ip>:8888/scotches/Ardbeg, http://<your docker host ip>:8888/scotches/Ardbeg similar to test the service."
- The R output is not quite the same as Python and Julia for the list of scotches or the similarity. Add a note in the README stating that the R output is not quite the same as the others. (It's just a multilanguage demo after all.)

Later on, in jupyter-incubator/kernel_gateway#39, we'll move the Python version over here too so that they all live in one spot.

**Comment by poplav** [comment]
Ok, The latest commit should reflect the changes noted in the comment above.

**Comment by parente** [comment]
:tada:

**Comment by poplav** [comment]
:laughing:, :koala::metal:

**Pull request merged**
