### PR TITLE
use latest python image

### LINKED ISSUE #63: ImportError: cannot import name 'Type'
After 

```
git clone https://github.com/jupyter/kernel_gateway_demos
cd kernel_gateway_demos/python_client_example
docker-compose build
```

the command 

`docker-compose up
`

produces the following error:

```
$ docker-compose up
Starting python_client_example_kernel_gateway_1 ... done
Starting python_client_example_nginx_1          ... done
Recreating python_client_example_client_1       ... done
Attaching to python_client_example_kernel_gateway_1, python_client_example_nginx_1, python_client_example_client_1
kernel_gateway_1  | [KernelGatewayApp] The Jupyter Kernel Gateway is running at: http://0.0.0.0:8888
client_1          | Traceback (most recent call last):
client_1          |   File "/src/client.py", line 5, in <module>
client_1          |     from tornado import gen
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 81, in <module>
client_1          |     from tornado.concurrent import (
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 34, in <module>
client_1          |     from tornado.log import app_log
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/log.py", line 34, in <module>
client_1          |     from tornado.escape import _unicode
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/escape.py", line 27, in <module>
client_1          |     from tornado.util import unicode_type
client_1          |   File "/usr/local/lib/python3.5/site-packages/tornado/util.py", line 21, in <module>
client_1          |     from typing import (
client_1          | ImportError: cannot import name 'Type'
python_client_example_client_1 exited with code 1

```

This was observed by others. [This answer](https://stackoverflow.com/a/55214031) indicates that this might due to an incompatibility of the installed versions of jupyter/tornado with python 3.5.

### PR DESCRIPTION
**Pull request by heiderich**
Fixes #63.

### CODE REVIEW

**Comment by echarles** [comment]
Works for me. A well defined version is better imho, e.g. `3.7.3-alpine3.9`

**Comment by heiderich** [comment]
What do others think? To me it is not clear which would be better. Choosing a fixed version may increase the likelihood that this will continue to function if the `python:latest` containers change quicker than this repository and may possibly lead to an incompatibility. Using `python:latest` has the advantage of revealing possible incompatibilities quicker. So I guess the question is whether you rather want it to work in a (possibly old) environment or rather detect incompatibilities at an early stage in the kernel gateway demos (and possibly the kernel gateway itself).

**Comment by nscozzaro** [comment]
Please pull it in to save others' time. I wasted an hour debugging it myself, just to then stumble across this pull request that already solves the issue.

**Review by kevin-bates — APPROVED** [review]
LGTM

**Pull request merged**
