### PR TITLE
More feature-filled nodejs client example

### PR DESCRIPTION
**Pull request by parente**
Move https://gist.github.com/parente/2d3ff03a2e4e1b0aa1c0 to here to become the nodejs example. Includes:
- jupyter-js-services 0.8
- nginx proxy
- docker-compose recipe
- easily replaceable python/scala snippets (defaults use spark)

### CODE REVIEW

**Comment by parente** [comment]
Makes it easier to test jupyter/jupyter-js-services#132

**Comment by jtyberg** [comment]
LGTM

**Comment by blink1073** [comment]
@dockter-84, do you mind taking this for a spin?

**Comment by dockter-84** [comment]
See https://github.com/jupyter/kernel_gateway_demos/issues/13

**Pull request merged**
